### ISSUE TITLE
[Request] - Creates a new user

### ISSUE THREAD

**Issue by jostmart** [lowlydba/lowlydba.sqlserver#130]
**Is your feature request related to a problem? Please describe.**

I need to add user(s) to database(s) with ansible

**Describe the solution you'd like**

Creates a new user for a specified database with provided specifications.
Like https://github.com/dataplat/dbatools/blob/master/functions/New-DbaDbUser.ps1

**Describe alternatives you've considered**

Manually doing this:

```
New-DbaDbUser -SqlInstance x-db2 -Database foobar -Login adminstage 
New-DbaDbUser -SqlInstance x-db2 -Database foobar -Login usrstage 

New-DbaDbUser -SqlInstance x-db2 -Database foobarAuth -Login adminstage 
New-DbaDbUser -SqlInstance x-db2 -Database foobarAuth -Login usrstage 

New-DbaDbUser -SqlInstance x-db2 -Database foobarOp -Login adminstage 
New-DbaDbUser -SqlInstance x-db2 -Database foobarOp -Login usrstage 

New-DbaDbUser -SqlInstance x-db2 -Database foobarSTAGE -Login adminstage 
New-DbaDbUser -SqlInstance x-db2 -Database foobarSTAGE -Login usrstage

New-DbaDbUser -SqlInstance x-db2 -Database foobarStatistics -Login adminstage 
New-DbaDbUser -SqlInstance x-db2 -Database foobarStatistics -Login usrstage  

```

**Comment by lowlydba** [comment]
I should have some time this weekend to get started on this, I think its a addition to the existing functionality.
