### ISSUE TITLE
[Bug] Can't restore DB to Azure SQL MI

### ISSUE THREAD

**Issue by Joey40** [lowlydba/lowlydba.sqlserver#140]
**Describe the bug**
Attempting to use `lowlydba.sqlserver.restore` results in: "Error restoring database: The parameter XpDirTree cannot be used with a Managed SQL Instance."

**To Reproduce**
Use `lowlydba.sqlserver.restore` against an Azure SQL Managed Instance

**Expected behavior**
The task should restore a database to the SQL Managed Instance

**Versions(please complete the following information):**

* OS: Ubuntu 20.04
* SQL Server: Azure SQL Managed Instance
* PowerShell: 7.3.0

**Additional context**
I believe this is a result of _plugins/modules/restore.ps1_ setting a default value for _xp_dirtree_, and there may be other parameters that are not expected for a SQL MI.

**Comment by lowlydba** [comment]
Thanks! I think your approach mentioned [here](https://github.com/lowlydba/lowlydba.sqlserver/discussions/137#discussioncomment-4275592) should work fine. It also probably will need a null check like the other non-defaulted params further down like: https://github.com/Joey40/lowlydba.sqlserver/blob/69d2c30438459d442433cdd4d00d53e073b33794/plugins/modules/restore.ps1#L108-L110

Feel free to open a PR!

**Comment by Joey40** [comment]
Added the null check and created the PR.
