### ISSUE TITLE
[Bug] existing login parameters

### ISSUE THREAD

**Issue by Joey40** [lowlydba/lowlydba.sqlserver#159]
I'm looking to add the ability to add/remove roles to logins. 

I noticed `$sa` referenced in a few places but it doesn't look like it's defined anywhere.  Should it be `$existingLogin` instead? 
https://github.com/lowlydba/lowlydba.sqlserver/blob/dbb925d200c09a13e05114ad90aa6ac03663add8/plugins/modules/login.ps1#L74

**Comment by lowlydba** [comment]
It definitely should! Some copy and paste errors from the `sa` module. Thanks for identifying!

**Comment by Joey40** [comment]
Do you want me to address that while I add the code for adding/removing roles?

**Comment by Joey40** [comment]
After going through the required changes, I think adding/removing roles should probably be it's own module.  I submitted a fix for this in the mean-time.
