### ISSUE TITLE
[Request] Diff mode support

### ISSUE THREAD

**Issue by lowlydba** [lowlydba/lowlydba.sqlserver#17]
Support diff mode for all modules.

**Comment by Joey40** [comment]
I'd be happy to help out with this if you can show me what it would look like for one of the modules, or at least work on one with me.

**Comment by lowlydba** [comment]
Upon further consideration, I think diff mode has minimal importance/relevance for this type of collection. With the effort involved and myself as the sole major maintainer at this time, I'm going to close this.
