### ISSUE TITLE
[Bug] Changing an agent schedules start time does not cause an update

### ISSUE THREAD

**Issue by OsirisDBA** [lowlydba/lowlydba.sqlserver#214]
On file: [plugins/modules/agent_job_schedule.ps1:116](https://github.com/lowlydba/lowlydba.sqlserver/blob/bee0380751c2fa0b26ec381fc4f9a166fcb33e85/plugins/modules/agent_job_schedule.ps1#L116)

The value ActiveEndTimeOfDay is repeated twice and ActiveStartTime is missing. This causes changes to be skipped if the only value updated was ActiveStartTime ( ie on a daily job )

**Comment by OsirisDBA** [comment]
PR: https://github.com/lowlydba/lowlydba.sqlserver/pull/215

**Comment by lowlydba** [comment]
Thanks for the issue and PR! Will try to get this released soon after merged.
