### ISSUE TITLE
[Request] logins configure roles too

### ISSUE THREAD

**Issue by DorBreger** [lowlydba/lowlydba.sqlserver#250]
**Is your feature request related to a problem? Please describe.**
when using the login module I would like to add roles too.
**Describe the solution you'd like**
Have another parameter of type list with all roles that will be granted to the login
**Describe alternatives you've considered**

**Additional context**

**Comment by lowlydba** [comment]
Are you thinking server roles or database roles?

**Comment by DorBreger** [comment]
Server

**Comment by lowlydba** [comment]
That seems like a good fit! It may make sense to also add a module for defining server roles as well to complement this.

**Comment by lowlydba** [comment]
So my schedule is going to be crazy for a while, and I thought I'd have time to work on this but likely will not. I did start getting the initial logic down, if you want to use it as a head start on making a PR. 

https://github.com/lowlydba/lowlydba.sqlserver/compare/add-roles-to-login?expand=1

**Comment by DorBreger** [comment]
seems like I need to be a collaborator for this link to work

**Comment by lowlydba** [comment]
Ah, sorry about that. Does this work? https://github.com/lowlydba/lowlydba.sqlserver/compare/main...add-roles-to-login

**Comment by lowlydba** [comment]
After implementing #290, I should have a good blueprint to do this for server roles too. It'll likely be its own module so you can more discretely add/remove individual roles. 

I am hoping the holidays give me some extra time to knock it out.

**Comment by DorBreger** [comment]
I wouldn't mind taking a jab at it myself if you are busy
