### ISSUE TITLE
Module for adding database to availability group

### ISSUE THREAD

**Issue by AmitaiSegal** [lowlydba/lowlydba.sqlserver#260]
I am not able to add an existing database to an availability group with the availavility_group module. I would like to get help with that if its possible with the availability_group module, if its not possible it would be great to have a module for that. Thanks

**Comment by lowlydba** [comment]
You can specify an existing database when you use the `availability_group` module to create or alter an availability group. Can you please include the following information

* Version of dbatools
* Version of lowlydba.sqlserver
* Version of SQL Server
* What error and/or output you receive when trying to do this
* The code you're attempting to do this with

**Comment by lowlydba** [comment]
@AmitaiSegal Please include more information for the issue you're having, otherwise this will need to be closed for lack of an MVP to reproduce the issue.
