### ISSUE TITLE
[Bug] dlevel broken via custom pwsh connection 'hack'

### ISSUE THREAD

**Issue by lowlydba** [lowlydba/lowlydba.sqlserver#275]
**Describe the bug**
On [dlevel tests](https://github.com/lowlydba/lowlydba.sqlserver/actions/runs/11753866104/job/32747206316#step:7:8801), `/setup_sqlserver_test_plugins/connection_plugins/local_pwsh.py` no longer works. Presumably this is from there being updates to the original python file that this replaces.

> The full traceback is:
Traceback (most recent call last):
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 176, in run
    res = self._execute()
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 610, in _execute
    self._connection = self._get_connection(cvars, templar, current_connection)
                       ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ansible/lib/ansible/executor/task_executor.py", line 992, in _get_connection
    connection, plugin_load_context = self._shared_loader_obj.connection_loader.get_with_context(
                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        conn_type,
        ^^^^^^^^^^
    ...<3 lines>...
        ansible_playbook_pid=to_text(os.getppid())
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/root/ansible/lib/ansible/plugins/loader.py", line 895, in get_with_context
    self._module_cache[path] = self._load_module_source(resolved_type_name, path)
                               ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/ansible/lib/ansible/plugins/loader.py", line 833, in _load_module_source
    spec.loader.exec_module(module)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/root/ansible_collections/lowlydba/sqlserver/tests/output/.tmp/integration/user-1rnoz0cd-ÅÑŚÌβŁÈ/tests/integration/targets/setup_sqlserver_test_plugins/connection_plugins/local_pwsh.py", line 30, in <module>
    from ansible.module_utils.compat import selectors
ImportError: cannot import name 'selectors' from 'ansible.module_utils.compat' (/root/ansible/lib/ansible/module_utils/compat/__init__.py)
fatal: [testhost]: FAILED! => {
    "msg": "Unexpected failure during module execution: cannot import name 'selectors' from 'ansible.module_utils.compat' (/root/ansible/lib/ansible/module_utils/compat/__init__.py)",
    "stdout": ""
}

**To Reproduce**
See all recent CI runs for Linux.

**Expected behavior**
We can use local pwsh to test this collection on the runner.

**Comment by lowlydba** [comment]
@briantist I haven't dug into this at all yet, but wanted to check in if you had seen it or were aware to avoid duplicating any efforts? 

No worries if not, I'll probably try to spend some time on it before the next minor release as it seems like it might be a blocker for the CI working .

**Comment by briantist** [comment]
I haven't looked at your actual CI results yet but it might be the same issue as this: 
- https://github.com/ansible-collections/community.hashi_vault/pull/459

**Comment by lowlydba** [comment]
Looks to be from https://github.com/ansible/ansible/commit/d2ba76c117f4dbab04c878350798b28b3a2f8485 - hopefully an easy adjusment...
