### ISSUE TITLE
[Bug] skip_password_reset parameter on login module makes playbook to fail when login does not exist

### ISSUE THREAD

**Issue by diegotercero** [lowlydba/lowlydba.sqlserver#282]
**Describe the bug**
The login module has a new parameter introduced in 2.3.0 that allows to avoid to reset the password of a SQL Server login in case this login already exists. 
When the user does not exist yet, this parameter results in a powershell interactive session where the user is expected to confirm the password of the new login to be created, causing the Ansible Playbook to fail.

**To Reproduce**
- Set the **skip_password_reset** to **true**.
- Make sure the login **name** and **password** parameters are set.
- Make sure the login does not exist yet in the target SQL Server Instance

**Expected behavior**
The login should be created just like when the skip_password_reset is not set.

**Versions :**
* OS: Windows Server 2019 with WSL 1 / Ubuntu 2024.04
* SQL Server: 2019
* PowerShell: 5.1
* Lowlydba.sqlserver: 2.3.3

** Attachment with bug output **

![2024-12-02_18-27-23](https://github.com/user-attachments/assets/4aaeb866-98d5-4a16-8f00-08c5e65d8b4a)

**Comment by lowlydba** [comment]
@diegotercero Thanks for the bug report! This should be quick to fix, I'll try to get it resolved shortly.
