### ISSUE TITLE
Normalize -WhatIf usage

### ISSUE THREAD

**Issue by lowlydba** [lowlydba/lowlydba.sqlserver#38]
Where possible, utilize -WhatIf for checkmode operations & standardize on _not_ trying to return artificial results for checkmode operations. DBATools has moved towards not giving normal output for -WhatIf and mocking it consistently in this collection is often tricky. Being consistent will be preferable.

This will be more thorough as it may surface parameter based issues handled by DBATools and reduce the number of nexted If statements too.

**Comment by briantist** [comment]
Consistency on output is good, the main thing I'd look at in Ansible for check mode support is returning appropriate status as to whether something will change or not, showing what will change isn't as important. 

This can sometimes be a challenge using `-WhatIf` alone.
