### ISSUE TITLE
Fix 'validate-modules' sanity test broken in CI

### ISSUE THREAD

**Issue by lowlydba** [lowlydba/lowlydba.sqlserver#6]
Running CI with modules present in the collection always throws the following error from `validate-modules`:

```
>>> Standard Error
[WARNING]: packaging Python module unavailable; unable to validate collection
Ansible version requirements
>>> Standard Output
{}
```

This appears to be an Ansible issue and not a failure due to the contents of the module, so it has been temporarily skipped until it can be resolved. 

May be related to https://github.com/ansible/ansible/issues/76504 

---

Test run: https://github.com/LowlyDBA/lowlydba.sqlserver/actions/runs/1801348265

**Comment by briantist** [comment]
this is weird.. the linked issue was fixed in December, although it doesn't seem to have been backported, which usually means it didn't need to be.

I'm curious also if this happens for us only in `devel`, we should try turning off fail-fast for sanity and re-running without the ignore just to confirm whether it's only devel or earlier versions too. We can also add `milestone` into the matrix at the same time; it's like `devel` but less up-to-date, intended to be newer than the latest stable branch, but still lagging behind `devel` in case of brand new breakages.

**Comment by LowlyDBA** [comment]
Good idea...looks like that isolated it to a change from 2.11 -> 2.12.

**Comment by briantist** [comment]
Nice, yeah from the test run we can see it's 2.12+, but I am still wondering why, there must be something related to the collection too, because this doesn't seem to be affecting any other collections that I can see. Maybe I can figure something out running it locally.

**Comment by briantist** [comment]
I did a little bit of local testing, but I'm coming up empty. 

I ran this using the `stable-2.12` branch (I have some issue with anything newer where the containers die, something unrelated):
```
python3.8 $(which ansible-test) sanity --docker default --docker-terminate never -vvvvv
```
(the weird invocation is because my default python is 3.6, and we need 3.8 minimum for 2.12+)

Here's the relevant output as text:
```
Run command: /root/.ansible/test/venv/sanity.validate-modules/3.9/2e4ce301/bin/python /root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate-modules --format  ...
Working directory: /root/ansible_collections/lowlydba/sqlserver
Program found: /root/.ansible/test/venv/sanity.validate-modules/3.9/2e4ce301/bin/python
ANSIBLE_COLLECTIONS_PATH=/root
ANSIBLE_CONFIG=/root/ansible/test/lib/ansible_test/_data/ansible.cfg
ANSIBLE_DEPRECATION_WARNINGS=false
ANSIBLE_DEVEL_WARNING=false
ANSIBLE_FORCE_COLOR=false
ANSIBLE_FORCE_HANDLERS=true
ANSIBLE_HOST_KEY_CHECKING=false
ANSIBLE_HOST_PATTERN_MISMATCH=error
ANSIBLE_INVENTORY=/dev/null
ANSIBLE_JINJA2_NATIVE_WARNING=false
ANSIBLE_LIBRARY=/dev/null
ANSIBLE_PYTHON_MODULE_RLIMIT_NOFILE=1024
ANSIBLE_RETRY_FILES_ENABLED=false
ANSIBLE_WORKER_SHUTDOWN_POLL_COUNT=100
ANSIBLE_WORKER_SHUTDOWN_POLL_DELAY=0.1
HOME=/root
LC_ALL=en_US.UTF-8
PAGER=/bin/cat
PATH=/root/ansible/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PYTHONPATH=/root/ansible/lib
Command exited with status 0 after 2.3649415969848633 seconds.
ERROR: Command "/root/.ansible/test/venv/sanity.validate-modules/3.9/2e4ce301/bin/python /root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate-modules --format json --arg-spec plugins/modules/memory.ps1 plugins/modules/memory.py --collection ansible_collections/lowlydba/sqlserver --collection-version 0.0.0" returned exit status 0.
>>> Standard Error
[WARNING]: packaging Python module unavailable; unable to validate collection
Ansible version requirements
>>> Standard Output
{}
Removing custom PyPI config: /root/.pydistutils.cfg
Removing custom PyPI config: /root/.pip/pip.conf
Command exited with status 1 after 18.381465673446655 seconds.
```
And as an image in case the colorization helps:
![image](https://user-images.githubusercontent.com/1260690/152669237-06a7da77-82af-47a8-83b9-702167825443.png)

---

Then I could shell into the container, and poke around:
```
root@2f04f7098ec1:/$ /root/.ansible/test/venv/sanity.validate-modules/3.9/2e4ce301/bin/python -m pip show packaging
WARNING: Package(s) not found: packaging
```

That's as expected.

```
root@2f04f7098ec1:/$ PYTHONPATH=/root/ansible/lib ANSIBLE_CONFIG=/root/ansible/test/lib/ansible_test/_data/ansible.cfg ANSIBLE_COLLECTIONS_PATH=/root /root/.ansible/test/venv/sanity.validate-modules/3.9/2e4ce301/bin/python /root/ansible/test/lib/ansible_test/_util/controller/sanity/validate-modules/validate-modules --format json --arg-spec plugins/modules/memory.ps1 plugins/modules/memory.py --collection ansible_collections/lowlydba/sqlserver --collection-version 0.0.0
{}
root@2f04f7098ec1:/$ echo $?
0
```

Also not unexpected since the output does say this command exits with `0`, but what I can't seem to get it to do is put anything out to `stderr`, so that message about packaging being missing is nowhere to be found.

So that's the extent of what I found (nothing basically).

**Comment by LowlyDBA** [comment]
The warning comes from [loader.py ](https://github.com/ansible/ansible/blob/ea34fdbfe2ad60d7100d6e54158ea137bf8e1aac/lib/ansible/plugins/loader.py), but not sure how exactly those two files are linked.

Adding it to the req file [sanity.validate-modules.in](https://github.com/ansible/ansible/blob/9a4ff01a4f9b96a310a61b576b77b6b42f51edc8/test/lib/ansible_test/_data/requirements/sanity.validate-modules.in) seems to fix it, but not sure if I'll need more clarifying details to get that fix accepted.

**Comment by LowlyDBA** [comment]
Other interesting observations:

* Only happens when a `.ps1` module file is present
* Does *not* occur if the `meta/runtime.yml` value is commented out

**Comment by briantist** [comment]
> The warning comes from [loader.py ](https://github.com/ansible/ansible/blob/ea34fdbfe2ad60d7100d6e54158ea137bf8e1aac/lib/ansible/plugins/loader.py), but not sure how exactly those two files are linked.
> 
> Adding it to the req file [sanity.validate-modules.in](https://github.com/ansible/ansible/blob/9a4ff01a4f9b96a310a61b576b77b6b42f51edc8/test/lib/ansible_test/_data/requirements/sanity.validate-modules.in) seems to fix it, but not sure if I'll need more clarifying details to get that fix accepted.

The reporter of the issue you linked tried to solve it that way and I believe that change was rejected in favor of the fix that changed the loader.

> Other interesting observations:
> 
> * Only happens when a `.ps1` module file is present
> * Does _not_ occur if the `meta/runtime.yml` value is commented out

Now THIS is good info.. I think we have enough to ask around about this and maybe file an issue. I'm going to do one other thing and check the Windows collections to see why their sanity tests are not failing.

**Comment by briantist** [comment]
It seems that if there's a single python module in the collection, the error will not be encountered and it all goes smoothly, so that's another piece to the puzzle. I will file an issue for this, and hopefully someone from core can take a look during the next week.
